name: CI

on:
  workflow_dispatch:
  pull_request:
    # paths:
    #   - "build.Dockerfile"
    #   - "Makefile"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    # strategy:
    #   matrix:
    #     platform:
    #       - linux/amd64
    #       - linux/arm64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: make docker-build

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: karnauskas/cloudflared-docker:latest
